services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports: ["3306:3306"]
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "ht159357"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --sql-mode="NO_ENGINE_SUBSTITUTION"
    working_dir: /var/lib/mysql
    restart: always