services:
  redis:
    container_name: redis
    image: redis:8.0.1
    ports: ["6379:6379"]
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: always
