name: Build Docker Image on Tag

on:
  push:
    tags:
      - '*:*'   # 形如 app:version 的 tag，例如 foo:1.0.0

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract app and version from tag
        id: tag
        run: |
          TAG_REF="${GITHUB_REF#refs/tags/}"
          APP="${TAG_REF%%:*}"
          VERSION="${TAG_REF#*:}"
          echo "app=$APP" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and Push Multi-Platform Image
        uses: docker/build-push-action@v5
        with:
          context: ./build/${{ steps.tag.outputs.app }}/${{ steps.tag.outputs.version }}
          file: ./build/${{ steps.tag.outputs.app }}/${{ steps.tag.outputs.version }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            yourdockerhubuser/${{ steps.tag.outputs.app }}:latest
            yourdockerhubuser/${{ steps.tag.outputs.app }}:${{ steps.tag.outputs.version }}
